force-app/main/default/objects/My_Offer__c/My_Offer__c.object-meta.xml
<CustomObject>
    <label>My Offer</label>
    <nameField>
        <label>My Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>My Offers</relationshipLabel>
    <relationshipName>My_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_1__c.field-meta.xml
<CustomField>
    <fullName>Tag_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 1</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers</relationshipLabel>
    <relationshipName>My_Offers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_2__c.field-meta.xml
<CustomField>
    <fullName>Tag_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 2</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers (Tag 2)</relationshipLabel>
    <relationshipName>My_Offers1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_3__c.field-meta.xml
<CustomField>
    <fullName>Tag_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 3</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers (Tag 3)</relationshipLabel>
    <relationshipName>My_Offers2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_4__c.field-meta.xml
<CustomField>
    <fullName>Tag_4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 4</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers (Tag 4)</relationshipLabel>
    <relationshipName>My_Offers3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getAccountRecord.cls
public with sharing class getAccountRecord {

  

    @AuraEnabled(cacheable=true)

    public static List<My_offer__c> getAccountRecordMethod(String recordIdAccount) {


      

        

    List<My_offer__c> accList=[SELECT Id, Name__c, Tag_1__c, Tag_2__c, Tag_3__c ,Tag_4__c, 	Documentation_URL__c, 	Description__c, Comment__c

        FROM My_offer__c

        Where Account__c=:recordIdAccount];

        Integer debugNumber = 0;

        for (Integer i = 0; i < accList.size(); i++) {

            debugNumber++;

            System.debug('name ' + accList.get(i).Name__c);


        }

        return accList;

    }

    

}