force-app/main/default/objects/My_Offer__c/My_Offer__c.object-meta.xml
<CustomObject>
    <label>My Offer</label>
    <nameField>
        <label>My Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>My Offers</relationshipLabel>
    <relationshipName>My_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_1__c.field-meta.xml
<CustomField>
    <fullName>Tag_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 1</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers</relationshipLabel>
    <relationshipName>My_Offers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_2__c.field-meta.xml
<CustomField>
    <fullName>Tag_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 2</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers (Tag 2)</relationshipLabel>
    <relationshipName>My_Offers1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_3__c.field-meta.xml
<CustomField>
    <fullName>Tag_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 3</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers (Tag 3)</relationshipLabel>
    <relationshipName>My_Offers2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/My_Offer__c/fields/Tag_4__c.field-meta.xml
<CustomField>
    <fullName>Tag_4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag 4</label>
    <referenceTo>Offer_Tag__c</referenceTo>
    <relationshipLabel>My Offers (Tag 4)</relationshipLabel>
    <relationshipName>My_Offers3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer_Tag__c/Offer_Tag__c.object-meta.xml
<CustomObject>
    <label>Offer Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/generateDataTest.cls
@isTest
public with sharing class generateDataTest {
    

    public static List<Account> generateAccountsTest(Integer accs, Integer offers){
    
            List<Account> accounts = new List<Account>();

            
        
            
        
            for(Integer i = 0 ; i<accs;i++){
        
              Account account = new Account();
              account.Name = 'test acc ' + i;
        
              accounts.add(account);
            }
            insert accounts;
        
            for(Account account : accounts){
              
        
              generateMyOffersAndAddOfferTags(account,offers);
        
            }

            return accounts;
        
          }
        
          public static void generateMyOffersAndAddOfferTags(Account account, Integer offerNum){
        
            List<Offer_Tag__c> offerTags = new List<Offer_Tag__c>();
            List<My_Offer__c> myOffers = new List<My_Offer__c>();
        
            for(Integer i = 0; i < offerNum; i++){
                            offerTags = generateOfferTags();
                            My_Offer__c myOffer1 = new My_Offer__c(
                                                    Account__c = account.id, 
                                                    Name__c = 'Investice ' + i, 
                                                    Tag_1__c = offerTags.get(0).Id, 
                                                    Tag_2__c = offerTags.get(1).Id, 
                                                    Tag_3__c = offerTags.get(2).Id, 
                                                    Tag_4__c = offerTags.get(3).Id 
                                                    );
        
                                         myOffers.add(myOffer1);
        
        
            }
            
                 insert myOffers;
          }
          
          public static List<Offer_Tag__c> generateOfferTags(){
        
            List<Offer_Tag__c> offerTags = new List<Offer_Tag__c>();
        
            for(Integer i = 0; i < 4; i++){
                Offer_Tag__c offerTag1 = new Offer_Tag__c(Name='Tag ' + i);
                offerTags.add(offerTag1);
            }
             
              insert offerTags;
        
              return offerTags;
        
          }
    }
    